# Generated by Django 5.2.17 on 2026-10-10 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64)),
                ('expira_en', models.DateTimeField()),
                ('consumida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacion_portal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de correo del portal',
                'verbose_name_plural': 'Verificaciones de correo del portal',
            },
        ),
    ]
