# Generated by Django 4.2.30 on 2026-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=30)),
                ('tipo', models.CharField(choices=[('PRIMERA', 'Primera consulta'), ('CONTROL', 'Control'), ('INFORME', 'Entrega de informe / examenes')], default='CONTROL', max_length=20)),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTE', 'No asistio')], default='AGENDADA', max_length=20)),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la consulta')),
                ('notas_internas', models.TextField(blank=True, help_text='Visible solo para el equipo, no para el paciente.', verbose_name='Notas internas')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Dia')),
                ('hora_inicio', models.TimeField(verbose_name='Desde')),
                ('hora_fin', models.TimeField(verbose_name='Hasta')),
                ('duracion_cita_minutos', models.PositiveSmallIntegerField(default=30, verbose_name='Duracion de cada hora (minutos)')),
                ('lugar', models.CharField(blank=True, help_text='Ej: Consulta particular, Clinica X.', max_length=150, verbose_name='Lugar de atencion')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
