# Generated by Django 5.2.17 on 2026-10-01 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='duracion_cita_minutos',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)], verbose_name='Duracion de cada hora (minutos)'),
        ),
    ]
