# Generated by Django 5.2.17 on 2026-10-10 23:55

import agenda.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_cita_duracion_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRIMERA', 'Primera consulta'), ('CONTROL', 'Control'), ('INFORME', 'Entrega de informe / examenes')], max_length=20, unique=True)),
                ('monto_clp', models.PositiveIntegerField(verbose_name='Monto en pesos chilenos')),
                ('activa', models.BooleanField(default=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa de servicio',
                'verbose_name_plural': 'Tarifas de servicios',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='PagoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('WEBPAY', 'Webpay'), ('PRESENCIAL', 'Pago en clínica')], max_length=12)),
                ('estado', models.CharField(choices=[('POR_PAGAR', 'Por pagar en clínica'), ('INICIADA', 'Pago Webpay iniciado'), ('PAGADA', 'Pagada'), ('FALLIDA', 'Pago rechazado'), ('EXPIRADA', 'Reserva expirada')], max_length=12)),
                ('monto_clp', models.PositiveIntegerField()),
                ('orden_compra', models.CharField(default=agenda.models.generar_orden_compra, max_length=26, unique=True)),
                ('sesion_id', models.CharField(default=agenda.models.generar_sesion_pago, max_length=32)),
                ('token_transbank', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=20)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='agenda.cita')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de cita',
                'verbose_name_plural': 'Pagos de citas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
