# Generated by Django 5.2.17 on 2026-10-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_tarifaservicio_pagocita'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocita',
            name='asignacion_vinculo_creado',
            field=models.BooleanField(default=False),
        ),
    ]
