# Generated by Django 4.2.30 on 2026-08-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesNeurologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semanas_gestacion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semanas de gestacion')),
                ('peso_nacimiento_gramos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso al nacer (gramos)')),
                ('tipo_parto', models.CharField(choices=[('VAGINAL', 'Parto vaginal'), ('CESAREA', 'Cesarea'), ('DESC', 'Desconocido')], default='DESC', max_length=10, verbose_name='Tipo de parto')),
                ('complicaciones_embarazo', models.TextField(blank=True, verbose_name='Complicaciones del embarazo o parto')),
                ('edad_sosten_cefalico', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sosten cefalico (meses)')),
                ('edad_sedestacion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Se sento solo (meses)')),
                ('edad_marcha', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Camino solo (meses)')),
                ('edad_primeras_palabras', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Primeras palabras (meses)')),
                ('observaciones_desarrollo', models.TextField(blank=True, verbose_name='Observaciones del desarrollo')),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Epilepsia, migrania, trastornos del aprendizaje, etc.', verbose_name='Antecedentes familiares')),
                ('antecedentes_morbidos', models.TextField(blank=True, verbose_name='Antecedentes morbidos y quirurgicos')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('medicamentos_actuales', models.TextField(blank=True, verbose_name='Medicamentos en uso')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Antecedentes neurologicos',
                'verbose_name_plural': 'Antecedentes neurologicos',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de la atencion')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('anamnesis', models.TextField(blank=True, help_text='Relato del tutor sobre lo que ocurre.', verbose_name='Anamnesis')),
                ('examen_fisico', models.TextField(blank=True, verbose_name='Examen fisico y neurologico')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('perimetro_cefalico_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Perimetro cefalico (cm)')),
                ('impresion_diagnostica', models.TextField(blank=True, verbose_name='Impresion diagnostica')),
                ('indicaciones', models.TextField(blank=True, verbose_name='Indicaciones y tratamiento')),
                ('examenes_solicitados', models.TextField(blank=True, help_text='Ej: EEG, resonancia, evaluacion fonoaudiologica.', verbose_name='Examenes solicitados')),
                ('derivaciones', models.TextField(blank=True, verbose_name='Derivaciones')),
                ('proximo_control', models.CharField(blank=True, help_text='Ej: en 3 meses', max_length=100, verbose_name='Proximo control')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atencion',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato 12345678-9. Si no tiene, usar el del pasaporte.', max_length=12, unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('prevision', models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('PARTICULAR', 'Particular'), ('OTRA', 'Otra')], default='FONASA', max_length=20, verbose_name='Prevision de salud')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('comuna', models.CharField(blank=True, max_length=80)),
                ('colegio', models.CharField(blank=True, max_length=150, verbose_name='Establecimiento educacional')),
                ('curso', models.CharField(blank=True, max_length=50)),
                ('derivado_por', models.CharField(blank=True, help_text='Profesional o institucion que deriva al paciente.', max_length=150, verbose_name='Derivado por')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('parentesco', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('ABUELO', 'Abuelo/a'), ('TUTOR', 'Tutor legal'), ('OTRO', 'Otro')], max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_principal', models.BooleanField(default=True, help_text='A este contacto se le envian los recordatorios de hora.', verbose_name='Contacto principal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Tutor / Apoderado',
                'verbose_name_plural': 'Tutores / Apoderados',
                'ordering': ['-es_principal', 'nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cie10', models.CharField(blank=True, help_text='Ej: G40.9 (epilepsia no especificada)', max_length=10, verbose_name='Codigo CIE-10')),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_diagnostico', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RESUELTO', 'Resuelto'), ('DESCARTADO', 'Descartado')], default='ACTIVO', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
                'ordering': ['-fecha_diagnostico'],
            },
        ),
    ]
