# Generated by Django 5.2.17 on 2026-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_asignacionprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionprofesional',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de termino'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tipo_atencion',
            field=models.CharField(blank=True, help_text='Ej: Neurologia, psicologia, fonoaudiologia.', max_length=100, verbose_name='Disciplina o servicio'),
        ),
    ]
