# Generated by Django 5.2.17 on 2026-10-10 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_asignacionprofesional_fecha_termino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta del tutor'),
        ),
        migrations.CreateModel(
            name='SolicitudAccesoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_rut', models.CharField(max_length=12, verbose_name='RUT de paciente solicitado')),
                ('parentesco', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('ABUELO', 'Abuelo/a'), ('TUTOR', 'Tutor legal'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión clínica'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_vinculo_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vinculo_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de acceso de tutor',
                'verbose_name_plural': 'Solicitudes de acceso de tutores',
                'ordering': ['estado', '-creada_en'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'paciente_rut'), name='solicitud_tutor_usuario_rut_unica')],
            },
        ),
    ]
