# Generated by Django 5.2.17 on 2026-09-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('DESACTIVAR', 'Desactivar'), ('ELIMINAR', 'Eliminar')], max_length=20),
        ),
    ]
