# Generated by Django 5.2.17 on 2026-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_auditoria_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profesion',
            field=models.CharField(blank=True, help_text='Ej: Medico, psicologo/a, fonoaudiologo/a.', max_length=100, verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('DESACTIVAR', 'Desactivar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAR', 'Consultar')], max_length=20),
        ),
    ]
