# Generated by Django 5.2.17 on 2026-10-01 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_profesion_alter_auditoria_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contrasenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de contraseña',
                'verbose_name_plural': 'Historial de contraseñas',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
