# Generated by Django 5.2.17 on 2026-10-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_fecha_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo verificado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_verificado',
            field=models.BooleanField(default=False, verbose_name='Telefono verificado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Medico'), ('SECRETARIA', 'Secretaria'), ('TUTOR', 'Tutor / paciente')], default='SECRETARIA', max_length=20, verbose_name='Rol'),
        ),
    ]
